{% set python_min = "3.10" %}
{% set name = "pc_rasterize" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UM-RMRS/pc-rasterize/releases/download/v{{ version }}/pc_rasterize-{{ version }}-sdist.tar.gz
  sha256: f6b8c15c77ce08fb30344871cf32c02f9bec905d948bd0674460ae55ae20a1fe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=64
  run:
    - python >={{ python_min }}
    - dask
    - geopandas
    - numba
    - numpy
    - odc-geo
    - pandas
    - pdal
    - python-pdal
    - rasterio
    - rioxarray
    - shapely >=2
    - xarray

test:
  requires:
    - python {{ python_min }}
  imports:
    - pc_rasterize

about:
  home: https://github.com/UM-RMRS/pc-rasterize
  summary: Rasterize point cloud data in parallel
  dev_url: https://github.com/UM-RMRS/pc-rasterize
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fbunt
