{% set python_min = "3.10" %}
{% set name = "pc_rasterize" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UM-RMRS/pc-rasterize/releases/download/v{{ version }}/pc_rasterize-{{ version }}-sdist.tar.gz
  sha256: 33e73015dee6ab445752935334fc5f50b2b2ca89c821398bed7fbefc41967f5e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=64
  run:
    - python >={{ python_min }}
    - dask
    - geopandas
    - numba
    - numpy
    - odc-geo
    - pandas
    - pdal
    - python-pdal
    - rasterio
    - rioxarray
    - shapely >=2
    - xarray

test:
  requires:
    - python {{ python_min }}
  imports:
    - pc_rasterize

about:
  home: https://github.com/UM-RMRS/pc-rasterize
  summary: Rasterize point cloud data in parallel
  dev_url: https://github.com/UM-RMRS/pc-rasterize
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fbunt
